version: '3.3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: persons
      POSTGRES_USER: person-svc
      POSTGRES_PASSWORD: person-svc
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '4'

  person-svc-go:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    deploy:
      resources:
        limits:
          memory: '1G'
          cpus: '2'
    image: person-svc-go:latest
    ports:
      - 8080:8080



