apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: person-svc-go
  name: person-svc-go
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: person-svc-go
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: person-svc-go
    spec:
      containers:
        - image: person-svc-go:latest
          name: person-svc-go
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: "1073741824"
      restartPolicy: Always
status: {}
