apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: persons
            - name: POSTGRES_PASSWORD
              value: person-svc
            - name: POSTGRES_USER
              value: person-svc
          image: postgres
          name: postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "4"
              memory: "536870912"
      restartPolicy: Always
status: {}
