apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: person-svc-go-dbv1
  name: person-svc-go-dbv1
spec:
  ports:
  - name: TCP-5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: person-svc-go-dbv1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
