apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: person-svc-go-dbv1
    deployment: person-svc-go-dbv1
  name: person-svc-go-dbv1
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: person-svc-go-dbv1
      deployment: person-svc-go-dbv1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: person-svc-go-dbv1
        deployment: person-svc-go-dbv1
      name: person-svc-go-dbv1
    spec:
      containers:
      - env:
        - name: MG_APP_NAME
          value: person-svc-go-dbv1
        - name: MG_API_VERSION
          value: 1.0.0
        - name: POSTGRES_USER
          value: person-svc
        - name: POSTGRES_PASSWORD
          value: person-svc
        - name: POSTGRES_DB
          value: persons
        image: docker.io/postgres:latest
        imagePullPolicy: IfNotPresent
        name: person-svc-go-dbv1
        resources: {}
status: {}
